---
- name: Ansible pull
  hosts: all
  become: true
  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart castle-pull.timer
      ansible.builtin.systemd:
        service: castle-pull.timer
        state: restarted

  tasks:
    - name: Install package dependencies
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - ansible

    - name: Install castle-pull.service
      ansible.builtin.template:
        src: etc_systemd_system_castle_pull.service.j2
        dest: /etc/systemd/system/castle-pull.service
        mode: "0o644"
      notify:
        - Reload systemd

    - name: Install castle-pull.timer
      ansible.builtin.template:
        src: etc_systemd_system_castle_pull.timer.j2
        dest: /etc/systemd/system/castle-pull.timer
        mode: "0o644"
      notify:
        - Reload systemd
        - Restart castle-pull.timer

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Enable castle-pull.timer
      ansible.builtin.systemd:
        service: castle-pull.timer
        state: started
        enabled: true
