---
ansible_pull_ref: main
ansible_pull_repository: https://github.com/adborden/castle.git
ansible_pull_playbook: site.yaml
ansible_pull_pgp_key_id: 00A43CCE8F0071D2FBA9873DAEE2B24D59FD94F6

vault_supplemental_groups:
  - step
