---
vault_image: docker.io/hashicorp/vault:2.0.0
vault_config_dir: /etc/vault
vault_data_dir: /var/lib/vault
vault_podman_args: ""
vault_publish_ports:
  - "8200:8200"

vault_disable_mlock: true
vault_listener_address: 127.0.0.1:8200
vault_listener_tls_cert_file: /etc/vault/cert.pem
vault_listener_tls_key_file: /etc/vault/key.pem
vault_listener_tls_min_version: tls13
vault_ui: true

vault_container_additional_volumes: []
vault_supplemental_groups: []
