name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: Gr1N/setup-poetry@v8

      - name: Cache poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with=dev

      - name: Install ansible roles
        run: poetry run ansible-galaxy install -r requirements.yaml --force

      - name: Run ansible-lint
        run: make lint

      - name: Run molecule test
        run: make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
